#!/bin/sh

### BEGIN INIT INFO
# Provides:          ptp4l
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: Run SpaceX ptp4l as an init daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

DAEMON=/usr/local/sbin/ptp4l
DEFAULTS=/etc/default/ptp4l
OPTIONS=

[ -r "$DEFAULTS" ] && . "$DEFAULTS"

. /lib/lsb/init-functions

if [ "$START_DAEMON" != "yes" ]; then
	log_daemon_msg "ptp4l server is disabled"
	exit 0
fi

case "$1" in
	start)
		log_daemon_msg "Starting ptp4l server"
		start-stop-daemon --start --quiet --oknodo --background --exec "$DAEMON" -- $OPTIONS
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping ptp4l server"
		start-stop-daemon --stop --quiet --oknodo --retry 2 --exec "$DAEMON"
		log_end_msg $?
		;;
	restart)
		$0 stop && sleep 1 && $0 start
		;;
	reload|force-reload)
		echo "Error: ptp4l '$1' not supported" >&2
		exit 3
		;;
	status)
		status_of_proc "$DAEMON" ptp4l
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|status}"
		exit 1
esac
